apiVersion: v1
appVersion: 6.2.3
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: entando-k8s-composite-app-controller
version: 6.2.3
